language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - extra-android-m2repository
    - extra-android-support
    - android-27

jdk:
  - oraclejdk8

script:
  - chmod +x gradlew
  - ./gradlew clean build --stacktrace --info


notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
